"""esquema inicial

Revision ID: 87f065d5fcff
Revises: 
Create Date: 2026-09-02 22:13:09.681087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f065d5fcff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_causa', sa.String(length=128), nullable=False),
    sa.Column('caratula', sa.String(length=512), nullable=False),
    sa.Column('juzgado_interviniente', sa.String(length=256), nullable=False),
    sa.Column('fiscalia_interviniente', sa.String(length=256), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTO', 'EN_CURSO', 'CERRADO_MANUAL', 'CERRADO_AUTOMATICO', name='estadocaso'), nullable=False),
    sa.Column('creado_por', sa.String(length=128), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cerrado_por', sa.String(length=128), nullable=True),
    sa.Column('motivo_cierre', sa.Text(), nullable=True),
    sa.Column('hash_reporte_final', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_numero_causa'), 'casos', ['numero_causa'], unique=True)
    op.create_table('ordenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('numero_orden', sa.String(length=128), nullable=False),
    sa.Column('juez_firmante', sa.String(length=256), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigente_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vigente_hasta', sa.DateTime(timezone=True), nullable=False),
    sa.Column('prorroga_hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prorroga_autorizada_por', sa.String(length=256), nullable=True),
    sa.Column('prorroga_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fundamento_proporcionalidad', sa.Text(), nullable=False),
    sa.Column('fundamento_necesidad', sa.Text(), nullable=False),
    sa.Column('fundamento_idoneidad', sa.Text(), nullable=False),
    sa.Column('imputado_identificacion', sa.String(length=512), nullable=False),
    sa.Column('defensor_nombre', sa.String(length=256), nullable=True),
    sa.Column('defensor_contacto', sa.String(length=256), nullable=True),
    sa.Column('estado', sa.Enum('VIGENTE', 'PRORROGADA', 'VENCIDA', 'CESADA', name='estadoorden'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ordenes_caso_id'), 'ordenes', ['caso_id'], unique=False)
    op.create_index(op.f('ix_ordenes_numero_orden'), 'ordenes', ['numero_orden'], unique=True)
    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('HOST_RED', 'API_BACKEND', 'DISPOSITIVO_MOVIL', 'OTRO', name='tipodispositivo'), nullable=False),
    sa.Column('identificador', sa.String(length=512), nullable=False),
    sa.Column('identificador_normalizado', sa.String(length=512), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sub_alcance_datos', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'AUTORIZADO_ACTIVO', 'OBJETIVO_CUMPLIDO', 'EXCLUIDO', name='estadodispositivo'), nullable=False),
    sa.Column('es_hallazgo_casual', sa.Boolean(), nullable=False),
    sa.Column('hallazgo_casual_origen_dispositivo_id', sa.Integer(), nullable=True),
    sa.Column('hallazgo_casual_aprobado_por', sa.String(length=256), nullable=True),
    sa.Column('hallazgo_casual_fecha_aprobacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cese_ejecutado', sa.Boolean(), nullable=False),
    sa.Column('cese_fecha', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cese_ejecutado_por', sa.String(length=128), nullable=True),
    sa.Column('cese_hash_verificacion', sa.String(length=64), nullable=True),
    sa.Column('cese_notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hallazgo_casual_origen_dispositivo_id'], ['dispositivos.id'], ),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispositivos_identificador'), 'dispositivos', ['identificador'], unique=False)
    op.create_index(op.f('ix_dispositivos_identificador_normalizado'), 'dispositivos', ['identificador_normalizado'], unique=False)
    op.create_index(op.f('ix_dispositivos_orden_id'), 'dispositivos', ['orden_id'], unique=False)
    op.create_table('personal_autorizado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('nombre_completo', sa.String(length=256), nullable=False),
    sa.Column('legajo', sa.String(length=64), nullable=True),
    sa.Column('rol_funcional', sa.String(length=128), nullable=False),
    sa.Column('autorizado_desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revocado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocado_motivo', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_autorizado_orden_id'), 'personal_autorizado', ['orden_id'], unique=False)
    op.create_index(op.f('ix_personal_autorizado_username'), 'personal_autorizado', ['username'], unique=False)
    op.create_table('eventos_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=True),
    sa.Column('secuencia', sa.Integer(), nullable=False),
    sa.Column('tipo_evento', sa.Enum('CASO_CREADO', 'ORDEN_CARGADA', 'DISPOSITIVO_AGREGADO', 'ACCION_AUTORIZADA', 'ACCION_RECHAZADA_GATING', 'HALLAZGO_IA_PROPUESTO', 'HALLAZGO_VALIDADO', 'HALLAZGO_DESCARTADO', 'HALLAZGO_CASUAL_DETECTADO', 'HALLAZGO_CASUAL_APROBADO', 'CESE_EJECUTADO', 'NOTIFICACION_GENERADA', 'SESION_CORTADA', 'CASO_CERRADO_MANUAL', 'CASO_CERRADO_AUTOMATICO', name='tipoevento'), nullable=False),
    sa.Column('actor_username', sa.String(length=128), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('detalle_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_iso', sa.String(length=64), nullable=False),
    sa.Column('hash_evento_anterior', sa.String(length=64), nullable=True),
    sa.Column('hash_evento', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_auditoria_caso_id'), 'eventos_auditoria', ['caso_id'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_dispositivo_id'), 'eventos_auditoria', ['dispositivo_id'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_hash_evento'), 'eventos_auditoria', ['hash_evento'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_secuencia'), 'eventos_auditoria', ['secuencia'], unique=False)
    op.create_index(op.f('ix_eventos_auditoria_tipo_evento'), 'eventos_auditoria', ['tipo_evento'], unique=False)
    op.create_table('hallazgos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('herramienta_origen', sa.String(length=128), nullable=False),
    sa.Column('comando_ejecutado', sa.Text(), nullable=False),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('cita_evidencia', sa.Text(), nullable=False),
    sa.Column('evidencia_cruda_hash', sa.String(length=64), nullable=False),
    sa.Column('severidad', sa.Enum('CRITICA', 'ALTA', 'MEDIA', 'BAJA', 'INFORMATIVA', name='severidadhallazgo'), nullable=False),
    sa.Column('confianza', sa.Enum('CONFIRMADA', 'PROBABLE', 'DESCARTADA', name='confianzahallazgo'), nullable=False),
    sa.Column('nvd_verificado', sa.Boolean(), nullable=False),
    sa.Column('nvd_score', sa.Float(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hallazgos_cve_id'), 'hallazgos', ['cve_id'], unique=False)
    op.create_index(op.f('ix_hallazgos_dispositivo_id'), 'hallazgos', ['dispositivo_id'], unique=False)
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'GENERADA', 'ENVIADA', 'ACUSE_RECIBIDO', name='estadonotificacion'), nullable=False),
    sa.Column('destinatario_nombre', sa.String(length=256), nullable=False),
    sa.Column('destinatario_rol', sa.String(length=64), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('generada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviada_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acuse_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hash_contenido', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificaciones_dispositivo_id'), 'notificaciones', ['dispositivo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificaciones_dispositivo_id'), table_name='notificaciones')
    op.drop_table('notificaciones')
    op.drop_index(op.f('ix_hallazgos_dispositivo_id'), table_name='hallazgos')
    op.drop_index(op.f('ix_hallazgos_cve_id'), table_name='hallazgos')
    op.drop_table('hallazgos')
    op.drop_index(op.f('ix_eventos_auditoria_tipo_evento'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_secuencia'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_hash_evento'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_dispositivo_id'), table_name='eventos_auditoria')
    op.drop_index(op.f('ix_eventos_auditoria_caso_id'), table_name='eventos_auditoria')
    op.drop_table('eventos_auditoria')
    op.drop_index(op.f('ix_personal_autorizado_username'), table_name='personal_autorizado')
    op.drop_index(op.f('ix_personal_autorizado_orden_id'), table_name='personal_autorizado')
    op.drop_table('personal_autorizado')
    op.drop_index(op.f('ix_dispositivos_orden_id'), table_name='dispositivos')
    op.drop_index(op.f('ix_dispositivos_identificador_normalizado'), table_name='dispositivos')
    op.drop_index(op.f('ix_dispositivos_identificador'), table_name='dispositivos')
    op.drop_table('dispositivos')
    op.drop_index(op.f('ix_ordenes_numero_orden'), table_name='ordenes')
    op.drop_index(op.f('ix_ordenes_caso_id'), table_name='ordenes')
    op.drop_table('ordenes')
    op.drop_index(op.f('ix_casos_numero_causa'), table_name='casos')
    op.drop_table('casos')
    # ### end Alembic commands ###
