"""agregar rango_red_autorizado a dispositivos

Revision ID: ac1315b98da2
Revises: 87f065d5fcff
Create Date: 2026-09-03 18:44:39.264037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1315b98da2'
down_revision: Union[str, None] = '87f065d5fcff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispositivos', sa.Column('rango_red_autorizado', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dispositivos', 'rango_red_autorizado')
    # ### end Alembic commands ###
